name: jetbot
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - tqdm
  - pip
  - pip:
    - opencv-contrib-python